PREFIX odsdr: <http://www.semanticweb.org/daniel-pontes/ontologies/2025/9/respiratory-diseases-ontology/>

SELECT ?doenca ?paciente
WHERE {
  ?paciente a odsdr:Paciente ;
            odsdr:recebeDiagnostico ?diagnostico .
  ?diagnostico odsdr:diagnosticaDoenca ?doenca .
}
ORDER BY ?doenca ?paciente
