PREFIX odsdr: <http://www.semanticweb.org/daniel-pontes/ontologies/2025/9/respiratory-diseases-ontology/>

SELECT ?doenca ?tratamento
WHERE {
  ?doenca a odsdr:Doenca ;
          odsdr:doencaRecebeTratamento ?tratamento .
}
ORDER BY ?doenca ?tratamento
